modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "clickthrough"
version = "${version}"
displayName = "ClickThrough Plus"
authors = "cassiancc"
description = '''
Click through Signs and Item Frames to Chests and other containers - a port of ClickThrough to Architectury.
'''
logoFile = "icon.png"
issueTrackerURL = "https://github.com/cassiancc/ClickThrough-Plus/issues"
displayURL="https://modrinth.com/mod/clickthrough+"
modURL="https://modrinth.com/mod/clickthrough+"

[[dependencies.clickthrough]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clickthrough]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clickthrough]]
modId = "architectury"
mandatory = true
versionRange = "[6.6.92,)"
ordering = "AFTER"
side = "BOTH"
