modLoader = "javafml"
loaderVersion = "[20,)"
license = "MIT"

[[mods]]
modId = "clickthrough"
version = "${version}"
displayName = "ClickThrough Plus"
authors = "cassiancc"
description = '''
Click through Signs and Item Frames to Chests and other containers - a port of ClickThrough to Architectury.
'''
logoFile = "assets/clickthrough/icon.png"
issueTrackerURL = "https://github.com/cassiancc/ClickThrough-Plus/issues"
displayURL="https://modrinth.com/mod/clickthrough+"
modURL="https://modrinth.com/mod/clickthrough+"

[[dependencies.clickthrough]]
modId = "neoforge"
type = "required"
versionRange = "[20.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clickthrough]]
modId = "minecraft"
type = "required"
versionRange = "[1.20,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.clickthrough]]
modId = "architectury"
type = "required"
versionRange = "[11.0.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "clickthrough.mixins.json"
